# docker-compose.yaml.
# Por: victorhugo.avila@enviame.io
# Definiciones para levantar tokyo en entorno local.
# Utiliza variables .env del directorio raiz y Dockerfile que se encuentra en la raiz.

version: '2'
services:
 base_gae:
  build: './'
  container_name: ${SERVICE_NAME}
  volumes:
   - ${CODE}:/app
   - ./deploy-conf/nginx/nginx-app.conf:/etc/nginx/conf.d/nginx-app.conf
  ports:
   - "${PORT}:8080"
  networks:
    - backend
# The Database
 mysql:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  container_name: oddomysql
  ports:
   - 33075:3306
  environment:
   MYSQL_ROOT_PASSWORD: 123
   MYSQL_DATABASE: wp_gli
   MYSQL_USER: root
   MYSQL_PASSWORD: 123
  networks:
   - backend
networks:
  backend:
    external:
      name: nbred
